baseURL = "https://datactivist.coop/"
defaultContentLanguage = "fr"
defaultContentLanguageInSubdir = true
removePathAccents = true
theme = ["datacthemist", "matomo"]
title = "Datactivist"
[languages.en]
contentDir = "content/english"
languageCode = "en-us"
languageName = "English"
title = "Datactivist"
[[languages.en.menu.lang]]
name = "Fr"
url = "/fr"
[[languages.en.menu.social]]
name = "github"
url = "https://github.com/datactivist"
weight = 100
[[languages.en.menu.social]]
name = "twitter"
url = "https://twitter.com/datactivi_st"
weight = 200
[languages.en.params]
footerAdress1 = "7 bis, Avenue Saint-Jérôme — 13100 Aix-en-Provence FRANCE"
footerAdress2 = ""
footerAlt = "Stickers"
footerButton = "OK !"
footerEmail = "Mail : hello@datactivist.coop"
footerImage = "images/stickers.png"
footerNewsletter = "Enter your email address (no spam, we promise !)"
[languages.fr]
contentDir = "content/francais"
languageCode = "fr_FR"
languageName = "Français"
title = "Datactivist"
[[languages.fr.menu.lang]]
name = "En"
url = "/en"
[[languages.fr.menu.main]]
name = "Blog"
url = "https://medium.com/datactivist"
weight = 300
[[languages.fr.menu.social]]
name = "github"
url = "https://github.com/datactivist"
weight = 100
[[languages.fr.menu.social]]
name = "twitter"
url = "https://twitter.com/datactivi_st"
weight = 200
[languages.fr.params]
footerAdress1 = "7 bis, Avenue Saint-Jérôme"
footerAdress2 = "13100 Aix-en-Provence"
footerAlt = "Stickers"
footerButton = "OK !"
footerEmail = "Mail : <a href='mailto:hello@datactivist.coop'>hello@datactivist.coop</a>"
footerImage = "images/stickers.png"
footerNewsletter = "Entrez votre email (pas de spam, promis !)"
footerMentionsLegales = "/mentionslegales/index.html"
[params]
logo = "/images/datactivist_logo.svg"
logoWhite = "/images/datactivist_logo-white.svg"
[taxonomies]
poste = "postes"
project = "projects"
tag = "tags"
[params.matomo]
url = "https://matomo.datactivist.coop"
id = 1
disableSRI = true
[params.matomo.track]
button = "Autoriser le suivi"
message = "J'autorise Datactivist à enregistrer des données de navigation à des fins statistiques."
[params.matomo.block]
button = "Bloquer le suivi"
message = "Aucune donnée de navigation ne sera conservée."