baseURL = "http://example.org/"
title = "My New Hugo Site"

theme = "Datacthemist"

defaultContentLanguage = "fr"
defaultContentLanguageInSubdir = true
removePathAccents=true

[languages]
[languages.en]
    languageCode = "en-us"
    title = "Datactivist en"
    contentDir = "content/english"
    languageName = "English"

[languages.fr]
  languageCode = "fr_FR"
  title = "Datactivist fr"
  contentDir = "content/français"
  languageName = "Français"

[[languages.fr.menu.main]]
  url    = "/fr/#"
  name   = "Blog"
  weight = 300

[[languages.fr.menu.social]]
url    = "/fr/#"
name   = "Github"
weight = 100

[[languages.fr.menu.social]]
url    = "/fr/#"
name   = "linkedin"
weight = 100