baseURL = "http://example.org/"
title = "My New Hugo Site"

theme = "Datacthemist"

defaultContentLanguage = "fr"
defaultContentLanguageInSubdir = true
removePathAccents=true

[params]
  logo = "/datactivist_logo.svg"

[languages]
[languages.en]
    languageCode = "en-us"
    title = "Datactivist"
    contentDir = "content/english"
    languageName = "English"

[languages.fr]
  languageCode = "fr_FR"
  title = "Datactivist"
  contentDir = "content/français"
  languageName = "Français"
  [languages.fr.params]
    footerEmail = "Mail : hello@datactivist.coop"
    footerAdress1 = "7 bis, Avenue Saint Jérome — 13100 Aix En Provence"
    footerAdress2 = "23, rue blondel — 75002 Paris"
    footerNewsletter = "Entrez votre email (pas de spam, promis !)"
    footerImage = "stickers.png"
    footerAlt = "Stickers"
    footerButton = "OK !"


[[languages.fr.menu.main]]
  url    = "/fr/#"
  name   = "Blog"
  weight = 300

[[languages.fr.menu.social]]
  url    = "https://github.com"
  name   = "github"

[[languages.fr.menu.social]]
  url    = "https://twitter.com"
  name   = "twitter"

