version: 2

jobs:
  # https://forestry.io/blog/automate-deploy-w-circle-ci/
  build:
    docker:
      - image: cibuilds/hugo:latest
    working_directory: ~/project
    steps:
      # 1. install git and checkout the repository
      # (2019-10 useless after switching to Ubuntu: https://github.com/cibuilds/hugo/issues/27)
      # - run: apt-get update && apt-get install git
      - checkout
      # 2. install submodules
      - run: rm -rf .git/modules/hugo/public/ .gitmodules hugo/public && git rm -r --cached hugo/public && git submodule add -b master git@github.com:datactivist/datactivist.github.io.git hugo/public
      # 3. install something to deploy to GH Pages?
      # 4. build with hugo
      - run: HUGO_ENV=production hugo -v -s ~/project/hugo -d public
      # 5. test with Htmlproofer
      - run: htmlproofer ~/project/hugo/public --allow-hash-href --check-html --empty-alt-ignore --disable-external
      # deploy the new version of the website by pushing public/ to datactivist.github.io
      # through the git submodule
      - add_ssh_keys:
          fingerprints:
            - "64:a9:a5:48:c0:03:4d:49:4a:05:08:bc:84:4c:05:87"
      - run: cd ~/project/hugo/public && git config user.email "circleci@circleci" && git config user.name "CircleCI" && git add . && git commit -m "[circle ci] deploy" && git push origin master

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only: master
